config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: {
      registrations: 'client/registrations',
      sessions: 'client/sessions'
    }
    scope module: :client do

      root 'home#index', as: :client_root
      resource :profiles, only: [:edit, :update, :show] do
        put :cancel
      end
      resources :addresses, except: :show
      resource :invite, only: :show
      resources :lottery, only: [:show, :index, :create]
      resources :shop
      resources :shares, only: [:show, :index]
      resources :prize, only: [:show, :update] do
        resource :feedback, only: [:show, :update]
      end
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace 'admin', path: '' do
      devise_for :users, controllers: {
        sessions: 'admin/sessions'
      }, as: :admin
      root 'home#index'
      resources :users, only: :index
      resources :items, except: :show do
        member do
          put :start
          put :pause
          put :end
          put :cancel
        end
      end
      resources :categories, except: :show
      resources :winners, only: :index do
        member do
          put :submit
          put :pay
          put :ship
          put :deliver
          put :publish
          put :remove_publish
        end
      end
      resources :orders, only: :index do
        member do
          put :pay
          put :cancel
        end
      end
      resources :offers, except: :show
      resources :bets, only: :index do
        put :cancel
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :regions, only: %i[index show], defaults: { format: :json } do
        resources :provinces, only: :index, defaults: { format: :json }
      end
      resources :provinces, only: %i[index show], defaults: { format: :json } do
        resources :cities, only: :index, defaults: { format: :json }
      end

      resources :cities, only: %i[index show], defaults: { format: :json } do
        resources :barangays, only: :index, defaults: { format: :json }
      end

      resources :barangays, only: %i[index show], defaults: { format: :json }
    end
  end
end

app/controllers/client/addresses_controller.rb
class Client::AddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_address, only: [:edit, :update, :destroy]

  def index
    @addresses = current_user.addresses
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.user = current_user
    if @address.save
      flash[:notice] = 'Address created successfully'
      redirect_to addresses_path
    else
      flash.now[:alert] = 'Address create failed'
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @address.update(address_params)
      flash[:notice] = 'Address updated successfully'
      redirect_to addresses_path
    else
      flash.now[:alert] = 'Address update failed'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @address.destroy
    flash[:notice] = 'Address destroyed successfully'
    redirect_to addresses_path
  end

  private

  def set_address
    @address = current_user.addresses.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:address_region_id, :address_province_id,
                                    :address_city_id, :address_barangay_id, :genre, :name,
                                    :street_address, :phone_number, :remark, :is_default)
  end
end

app/controllers/client/feedbacks_controller.rb
class Client::FeedbacksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_winner

  def show; end

  def update
    if @winner.may_share? && @winner.update(winner_params)
      @winner.share!
      flash[:notice] = "Successfully updated"
      redirect_to profiles_path(category: 'winning')
    else
      render :show
    end
  end

  private

  def set_winner
    @winner = current_user.winners.delivered.find(params[:prize_id])
  end

  def winner_params
    params.require(:winner).permit(:comment, :picture)
  end

end

app/controllers/client/home_controller.rb
class Client::HomeController < ApplicationController
  def index; end
end

app/controllers/client/invites_controller.rb
class Client::InvitesController < ApplicationController
  before_action :authenticate_user!

  def show
    @promote_url = "#{request.host_with_port}#{new_user_registration_path}?promoter=#{current_user.email}"
    qrcode = RQRCode::QRCode.new(@promote_url)

    @svg = qrcode.as_svg(offset: 0, color: "000", shape_rendering: 'crispEdges',
                         module_size: 6, standalone: true)
  end
end

app/controllers/client/lottery_controller.rb
class Client::LotteryController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @items = Item.active.starting.where("offline_at >= (?) AND online_at <= (?)", Date.current, Date.current)
    @items = @items.includes(:categories).where(categories: { id: params[:category] }) if params[:category].present?
  end

  def show
    @item = Item.active.starting.where("offline_at >= (?) AND online_at <= (?)", Date.current, Date.current).find(params[:id])
    @bet = Bet.new
    @bets = current_user.bets.where(item: @item, batch_count: @item.batch_count)
    @progress = (Bet.where(item: @item, batch_count: @item.batch_count).count/@item.minimum_bets.to_f) * 100
  end

  def create
    bet_counts = params[:bet][:bet_count]
    bet_counts.to_i.times do |bet_count|
      bet = Bet.create(batch_count: params[:item_batch_count],
                     user_id: current_user.id, item_id: params[:item_id])
      if bet.errors.any?
        flash[:notice] = "#{bet.errors.full_messages}, #{bet_count} bets created"
        break
      elsif bet_count == bet_counts.to_i
        flash[:notice] = 'Successfully created'
      end
    end
    redirect_to lottery_path(id: params[:item_id])
  end

end

app/controllers/client/prize_controller.rb
class Client::PrizeController < ApplicationController
  def show
    @winner = Winner.find(params[:id])
  end

  def update
    @winner = Winner.won.find(params[:id])
    if @winner.update(address_id: params[:winner][:address_id])
      @winner.claim!
      flash[:notice] = "Successfully updated"
      redirect_to profiles_path(category: 'winning')
    else
      flash[:alert] = "Fail to update"
      render :show
    end
  end

end

app/controllers/client/profiles_controller.rb
class Client::ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @orders = current_user.orders if params[:category] == 'orders'
    @bets = current_user.bets if params[:category] == 'lottery'
    @members = current_user.children if params[:category] == 'invites'
    @winnings = current_user.winners if params[:category] == 'winning'
  end

  def edit
    @client = current_user
  end

  def update
    @client = current_user

    if @client.update(update_without_password_params)
      redirect_to profiles_path, notice: "Successfully Updated"
    else
      @client.update(update_with_password_params)
      redirect_to profiles_path, notice: "Successfully Updated"
    end
  end

  def cancel
    @order = Order.find(params[:id])
    if @order.cancel!
      flash[:notice] = 'Cancelled Successfully'
    else
      flash[:alert] = @order.errors.full_messages.join(', ')
    end
    redirect_to profiles_path(category: 'orders')
  end

  private

  def client_params
  end

  def update_without_password_params
    params.require(:user).permit(:phone_number, :username, :image)
  end

  def update_with_password_params
    params.require(:user).permit(:username, :email, :phone_number, :image, :password)
  end
end

app/controllers/client/registrations_controller.rb
# frozen_string_literal: true

class Client::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    cookies[:promoter] ||= params[:promoter]
    super
  end

  # POST /resource
  def create
    super
    parent = User.find_by(email: cookies[:promoter])
    self.resource.update(parent: parent)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/client/sessions_controller.rb
# frozen_string_literal: true

class Client::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end
  def create
    user = User.find_by(email: params[:user][:email])
    if user&.client?
      super
    else
      flash[:alert] = "Wrong email or password"
      redirect_to new_user_session_path
    end
  end
  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/client/shares_controller.rb
class Client::SharesController < ApplicationController
  before_action :set_winner, only: :show

  def show; end

  def index
    @winners = Winner.published
  end

  private

  def set_winner
    @winner = Winner.includes(:user).find(params[:id])
  end
end

app/controllers/client/shop_controller.rb
class Client::ShopController < ApplicationController
  before_action :authenticate_user!, only: :create
  before_action :set_offer, except: [:index, :create]

  def index
    @offers = Offer.active
  end

  def show
    @offer = Offer.find(params[:id])
    @order = Order.new
  end

  def create
    @offer = Offer.find_by(id: params[:order][:offer_id])
    @order = Order.new(offer_id: @offer.id)
    @order.amount = @offer.amount
    @order.coin = @offer.coins
    @order.user = current_user
    @order.genre = :deposit
    @order.offer = @offer
    if @order.save
      @order.submit!
      flash[:notice] = "Your purchase is complete"
    else
      flash[:alert] = @order.errors.full_messages.join(', ')
    end
    redirect_to shop_index_path
  end

  private

  def set_offer
    @offer = Offer.active.find(params[:id])
  end

end

app/helpers/client/home_helper.rb
module Client::HomeHelper
end

app/views/client/profiles/edit.html.erb
<div class="d-flex justify-content-center align-items-center" style="height: 60vh;">
  <div class="card text-center">
    <h3 class="text-center">Edit Profile</h3>
    <div class="card-body">

      <%= form_with(model: current_user, url: profiles_path, method: :patch) do |form| %>

        <div class="form-group mb-3">
          <% form.label :username, class: "form-label" %>
          <%= form.text_field :username, class: "form-control", placeholder: "Username" %>
        </div>

        <div class="form-group mb-3">
          <% form.label :Phone_number, class: "form-label" %>
          <%= form.text_field :phone_number, class: "form-control", placeholder: "Phone Number" %>
        </div>

        <div class="form-group mb-3">
          <% form.label :password, class: "form-label" %>
          <%= form.text_field :password, class: "form-control", placeholder: "Password" %>
        </div>


        <div class="form-group mb-3">
          <%= form.file_field :image, class: "form-control" %>
        </div>

        <%= form.submit "Update", class: "btn btn-secondary w-100"%>
      <% end %>
    </div>
  </div>
</div>

app/views/client/profiles/show.html.erb
<div class="d-flex justify-content-center align-items-center" style="height: 80vh;">
  <div class="text-start">
    <div class="card">
      <div class="card-body text-start d-flex flex-wrap align-items-center justify-content-between">
        <div class="d-flex align-items-center">
          <%# if current_user && current_user.image.present? %>
          <%#= image_tag current_user.image.url, class: "avatar-image", style: "width: 300px; height: 300px;" %>
          <%# else %>
          <%#= image_tag "avatar.png", class: "avatar-image", style: "width: 300px; height: 300px;" %>
          <%# end %>

          <div class="ms-3">
            <p class="nav-link active" aria-current="page">
              Username: <%= current_user ? current_user.username : '' %>
            </p>
            <p class="nav-link active" aria-current="page">
              Email: <%= current_user ? current_user.email : '' %>
            </p>
            <p class="nav-link active" aria-current="page">
              Phone Number: <%= current_user ? current_user.phone_number : '' %>
            </p>
            <p class="nav-link active" aria-current="page">
              Coins: <%= current_user ? current_user.coins : '' %>
            </p>
          </div>
        </div>

        <div class="w-100 mt-auto">
          <div class="d-flex justify-content-center">
            <a href="#" class="btn btn-secondary w-100">Cash in</a>
          </div>
          <div class="d-flex justify-content-center gap-1 mt-2">
            <%= link_to "Edit Profile", edit_profiles_path, class: "btn btn-secondary w-100" %>
            <%= link_to "Address", addresses_path, class: "btn btn-secondary w-100" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container" style="margin-bottom: 90px">
  <div class="row" role="group" aria-label="Basic radio toggle button group">
    <%= link_to 'Order History', profiles_path(category: :orders), class: 'btn btn-outline-secondary w-25' %>
    <%= link_to 'Lottery History', profiles_path(category: :lottery), class: 'btn btn-outline-secondary w-25' %>
    <%= link_to 'Winning History', profiles_path(category: :winning), class: 'btn btn-outline-secondary w-25' %>
    <%= link_to 'Invitation History', profiles_path(category: :invites), class: 'btn btn-outline-secondary w-25' %>
  </div>


  <% if params[:category] == 'orders' %>
    <% @orders.each do |order| %>
      <div class="row">
        <div class="card w-100">
          <div class="card-body">
            <div><b>Serial Number: </b><%= order.serial_number %></div>
            <div><b>Coin: </b><%= order.coin %></div>
            <div><b>Amount: </b><%= order.amount %></div>
            <div><b>State: </b><%= order.state %></div>
            <div><b>Date Created: </b><%= order.created_at %></div>
          </div>
          <%= button_to 'Cancel Order', cancel_profiles_path(id: order), method: :put, class: 'btn btn-secondary w-100', data: { turbo: false } if order.may_cancel? %>
        </div>
      </div>
    <% end %>
  <% end %>

  <% if params[:category] == 'lottery' %>
    <% @bets.each do |bet| %>
      <div class="card w-100" style=" margin-top:10px">
        <div class="card-body">
          <div><b>Serial Number: </b><%= bet.serial_number %></div>
          <div><b>Coins: </b><%= bet.coins %></div>
          <div><b>State: </b><%= bet.state %></div>
          <div><b>Item Name: </b><%= bet.item.name %></div>
          <div><b>Date Created: </b><%= bet.created_at %></div>
        </div>
      </div>
    <% end %>
  <% end %>

  <% if params[:category] == 'winning' %>
    <% @winnings.each do |winner| %>
      <div class="card" style=" margin-top:10px">
        <div class="card-body">
          <div><b>Serial Number: </b><%= winner.bet.serial_number %></div>
          <div><b>Item Name: </b><%= winner.item.name %></div>
          <div><b>Date Created: </b><%= winner.created_at %></div>
          <div><b>State: </b><%= winner.state %></div>
        </div>
        <%= link_to "Claim Prize", prize_path(winner), class: 'btn btn-secondary' if winner.may_claim? %>
        <%= link_to "Share Feedback", prize_feedback_path(winner), class: 'btn btn-secondary' if winner.may_share? %>
      </div>

    <% end %>
  <% end %>

  <% if params[:category] == 'invites' %>
    <% @members.each do |member| %>
      <div class="card w-100" style=" margin-top:10px">
        <div class="card-body">
          <div><b>Username: </b><%= member.username %></div>
          <div><b>Email: </b><%= member.email %></div>
          <div><b>Date Invited: </b><%= member.created_at %></div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>