config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: {
      registrations: 'client/registrations',
      sessions: 'client/sessions'
    }
    scope module: :client do

      root 'home#index', as: :client_root
      resource :profiles, only: [:edit, :update, :show] do
        put :cancel
      end
      resources :addresses, except: :show
      resource :invite, only: :show
      resources :lottery, only: [:show, :index, :create]
      resources :shop
      resources :shares, only: [:show, :index]
      resources :prize, only: [:show, :update] do
        resource :feedback, only: [:show, :update]
      end
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace 'admin', path: '' do
      devise_for :users, controllers: {
        sessions: 'admin/sessions'
      }, as: :admin
      root 'home#index'
      resources :users, only: :index
      resources :items, except: :show do
        member do
          put :start
          put :pause
          put :end
          put :cancel
        end
      end
      resources :categories, except: :show
      resources :winners, only: :index do
        member do
          put :submit
          put :pay
          put :ship
          put :deliver
          put :publish
          put :remove_publish
        end
      end
      resources :orders, only: :index do
        member do
          put :pay
          put :cancel
        end
      end
      resources :offers, except: :show
      resources :bets, only: :index do
        put :cancel
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :regions, only: %i[index show], defaults: { format: :json } do
        resources :provinces, only: :index, defaults: { format: :json }
      end
      resources :provinces, only: %i[index show], defaults: { format: :json } do
        resources :cities, only: :index, defaults: { format: :json }
      end

      resources :cities, only: %i[index show], defaults: { format: :json } do
        resources :barangays, only: :index, defaults: { format: :json }
      end

      resources :barangays, only: %i[index show], defaults: { format: :json }
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM
  enum genre: { deposit: 0, increase: 1, deduct: 2, bonus: 3, share: 4 }

  belongs_to :user
  belongs_to :offer, optional: true
  after_create :assign_serial_number

  aasm column: :state do
    state :pending, initial: true
    state :submitted, :cancelled, :paid

    event :submit do
      transitions from: :pending, to: :submitted
    end

    event :cancel do
      transitions from: [:submitted, :pending], to: :cancelled
      transitions from: :paid, to: :cancelled, guard: :can_cancel_increase?, after: [:update_user_coin_on_cancel, :decrease_total_deposit]
    end

    event :pay do
      transitions from: :submitted, to: :paid, guard: :can_deduct?, after: [:update_user_coin_on_pay, :increase_total_deposit]
    end
  end

  def update_user_coin_on_pay
    if deduct?
      user.update(coins: user.coins - coin)
    else
      user.update(coins: user.coins + coin)
    end
  end

  def increase_total_deposit
    user.update(total_deposit: user.total_deposit + amount) if deposit?
  end

  def update_user_coin_on_cancel
    if deduct?
      user.update(coins: user.coins + coin)
    else
      user.update(coins: user.coins - coin)
    end
  end

  def decrease_total_deposit
    user.update(total_deposit: user.total_deposit - amount) if deposit?
  end

  def can_cancel_increase?
    (!deduct? && user.coins >= coin) || deduct?
  end

  def can_deduct?
    (deduct? && user.coins >= coin) || !deduct?
  end

  def assign_serial_number
    number_count = user.orders.count.to_s
    date = Time.current.strftime('%y%m%d')
    self.update(serial_number: "#{date}-#{id}-#{user.id}-#{number_count.rjust(4, '0')}")
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_order, except: :index

  def index
    @orders = Order.includes(:user, :offer).all
    @orders = @orders.where(serial_number: params[:serial_number]) if params[:serial_number].present?
    @orders = @orders.where(user: { email: params[:email] }) if params[:email].present?
    @orders = @orders.where(state: params[:state]) if params[:state].present?
    @orders = @orders.where(genre: params[:genre]) if params[:genre].present?
    @orders = @orders.where(offer: { genre: params[:offer_genre] }) if params[:offer].present?
    @orders = @orders.where("created_at >= (?)", params[:start_date]) if params[:start_date].present?
    @orders = @orders.where("created_at <= (?)", params[:end_date]) if params[:end_date].present?
    @amount_total = @orders.sum(&:amount)
    @coin_total = @orders.sum(&:coin)
    @orders = @orders.page(params[:page]).per(5)
    @amount_subtotal = @orders.sum(&:amount)
    @coin_subtotal = @orders.sum(&:coin)
  end

  def pay
    if @order.pay!
      flash[:notice] = 'Order Successfully Paid'
    else
      flash[:alert] = 'Payment Unsuccessful'
    end
    redirect_to admin_orders_path
  end

  def cancel
    if @order.cancel!
      flash[:notice] = 'Cancelled successfully'
    end
    redirect_to admin_orders_path
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end
end

app/views/admin/orders/index.html.erb
<%= form_tag admin_orders_path, data: { turbo: false }, method: :get do %>
  <div class="row">
    <div class="col-3">
      <%= label_tag :serial_number, 'Serial Number', class: 'form-label' %>
      <%= text_field_tag :serial_number, params[:serial_number], class: 'form-control' %>
    </div>

    <div class="col-4">
      <%= label_tag :genre, 'Genre', class: 'form-label' %>
      <%= select_tag :genre, options_for_select(Order.genres.map{|o|[o.first.humanize, o.first]}), prompt: 'Select genre', class: 'form-control' %>
    </div>

    <div class="col-4">
      <%= label_tag :genre, 'Offer Genre', class: 'form-label' %>
      <%= select_tag :genre, options_for_select(Offer.genres.map{|o|[o.first.humanize, o.first]}), prompt: 'Select offer', class: 'form-control' %>
    </div>

    <div class="col-5">
      <%= label_tag :email, 'Email', class: 'form-label' %>
      <%= text_field_tag :email, params[:email], class: 'form-control' %>
    </div>

    <div class="col-4">
      <%= label_tag :state, 'State', class: 'form-label' %>
      <%= select_tag :state, options_for_select(Order.aasm.states.map{|state| [state.name, state.name]}, params[:state]), class: 'form-control' %>
    </div>

    <div class="col-4">
      <%= label_tag :start_date, 'Start Date', class: 'form-label' %>
      <%= datetime_field_tag :start_date, params[:start_date], class: 'form-control' %>
    </div>

    <div class="col-4">
      <%= label_tag :end_date, 'End Date', class: 'form-label' %>
      <%= datetime_field_tag :end_date, params[:end_date], class: 'form-control' %>
    </div>

    <div class="my-3">
      <%= submit_tag 'Search', class: 'btn btn-secondary'%>
    </div>
  </div>
<% end %>


<table class="table">
  <thead>
  <tr>
    <th>Serial Number</th>
    <th>User Email</th>
    <th>Amount</th>
    <th>Coin</th>
    <th>State</th>
    <th>Offer</th>
    <th>Genre</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.serial_number %></td>
      <td><%= order.user.email %></td>
      <td><%= order.amount %></td>
      <td><%= order.coin %></td>
      <td><%= order.state %></td>
      <td><%= order.offer&.genre %></td>
      <td><%= order.genre %></td>
      <td>
        <%= button_to 'Pay', pay_admin_order_path(order), method: :put, data: { turbo: false } if order.may_pay? %>
        <%= button_to 'Cancel', cancel_admin_order_path(order), method: :put if order.may_cancel? %>
      </td>
    </tr>
  <% end %>
  <tr>
    <td>Subtotal</td>
    <td></td>
    <td><%= @amount_subtotal %></td>
    <td><%= @coin_subtotal %></td>
    <td colspan="4"></td>
  </tr>
  <tr>
    <td>Total</td>
    <td></td>
    <td><%= @amount_total %></td>
    <td><%= @coin_total %></td>
    <td colspan="4"></td>
  </tr>
  </tbody>
</table>

<%= paginate @orders %>