config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: {
      registrations: 'client/registrations',
      sessions: 'client/sessions'
    }
    scope module: :client do

      root 'home#index', as: :client_root
      resource :profiles, only: [:edit, :update, :show] do
        put :cancel
      end
      resources :addresses, except: :show
      resource :invite, only: :show
      resources :lottery, only: [:show, :index, :create]
      resources :shop
      resources :shares, only: [:show, :index]
      resources :prize, only: [:show, :update] do
        resource :feedback, only: [:show, :update]
      end
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace 'admin', path: '' do
      devise_for :users, controllers: {
        sessions: 'admin/sessions'
      }, as: :admin
      root 'home#index'
      resources :users, only: :index
      resources :items, except: :show do
        member do
          put :start
          put :pause
          put :end
          put :cancel
        end
      end
      resources :categories, except: :show
      resources :winners, only: :index do
        member do
          put :submit
          put :pay
          put :ship
          put :deliver
          put :publish
          put :remove_publish
        end
      end
      resources :orders, only: :index do
        member do
          put :pay
          put :cancel
        end
      end
      resources :offers, except: :show
      resources :bets, only: :index do
        put :cancel
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :regions, only: %i[index show], defaults: { format: :json } do
        resources :provinces, only: :index, defaults: { format: :json }
      end
      resources :provinces, only: %i[index show], defaults: { format: :json } do
        resources :cities, only: :index, defaults: { format: :json }
      end

      resources :cities, only: %i[index show], defaults: { format: :json } do
        resources :barangays, only: :index, defaults: { format: :json }
      end

      resources :barangays, only: %i[index show], defaults: { format: :json }
    end
  end
end

app/models/winner.rb
class Winner < ApplicationRecord
  include AASM

  belongs_to :user
  belongs_to :item
  belongs_to :admin, class_name: 'User', foreign_key: 'admin_id', optional: true
  belongs_to :address, optional: true
  belongs_to :bet

  mount_uploader :picture, ImageUploader

  aasm column: :state do
    state :won, initial: true
    state :claimed, :submitted, :paid, :shipped, :delivered, :shared,
          :published, :remove_published

    event :claim do
      transitions from: :won, to: :claimed
    end

    event :submit do
      transitions from: :claimed, to: :submitted
    end

    event :pay do
      transitions from: :submitted, to: :paid
    end

    event :ship do
      transitions from: :paid, to: :shipped
    end

    event :deliver do
      transitions from: :shipped, to: :delivered
    end

    event :share do
      transitions from: :delivered, to: :shared
    end

    event :publish do
      transitions from: :shared, to: :published
      transitions from: :remove_published, to: :published
    end

    event :remove_publish do
      transitions from: :published, to: :remove_published
    end
  end

end

app/controllers/admin/winners_controller.rb
class Admin::WinnersController < AdminController
  before_action :set_winner, except: :index
  def index
    @winners = Winner.all
    @winners = @winners.where(serial_number: params[:serial_number]) if params[:serial_number].present?
    @winners = @winners.includes(:user).where(user: {email: params[:email]}) if params[:email].present?
    @winners = @winners.where(state: params[:state]) if params[:state].present?
    @winners = @winners.where("created_at >= (?)", params[:start_date]) if params[:start_date].present?
    @winners = @winners.where("created_at <= (?)", params[:end_date]) if params[:end_date].present?
  end


  def submit
    if @winner.submit!
      flash[:notice] = 'Submitted successfully'
    end
    redirect_to admin_winners_path
  end

  def pay
    if @winner.pay!
      flash[:notice] = 'Paid successfully'
    end
    redirect_to admin_winners_path
  end

  def ship
    if @winner.ship!
      flash[:notice] = 'Shipped successfully'
    end
    redirect_to admin_winners_path
  end

  def deliver
    if @winner.deliver!
      flash[:notice] = 'Delivered successfully'
    end
    redirect_to admin_winners_path
  end


  def publish
    if @winner.publish!
      flash[:notice] = 'Published successfully'
    end
    redirect_to admin_winners_path
  end

  def remove_publish
    if @winner.remove_publish!
      flash[:notice] = 'Removed publish successfully'
    end
    redirect_to admin_winners_path
  end

  private

  def set_winner
    @winner = Winner.find(params[:id])
  end
end

app/views/admin/winners/index.html.erb
<%= form_tag admin_winners_path, data: { turbo: false }, method: :get do %>
  <div class="row">
    <div class="col-3">
      <%= label_tag :serial_number, 'Serial Number', class: 'form-label' %>
      <%= text_field_tag :serial_number, params[:serial_number], class: 'form-control' %>
    </div>

    <div class="col-5">
      <%= label_tag :email, 'Email', class: 'form-label' %>
      <%= text_field_tag :email, params[:email], class: 'form-control' %>
    </div>

    <div class="col-4">
      <%= label_tag :state, 'State', class: 'form-label' %>
      <%= select_tag :state, options_for_select(Winner.aasm.states.map{|state| [state.name, state.name]}, params[:state]),  include_blank: 'all', class: 'form-control' %>
    </div>

    <div class="col-4">
      <%= label_tag :start_date, 'Start Date', class: 'form-label' %>
      <%= datetime_field_tag :start_date, params[:start_date], class: 'form-control' %>
    </div>

    <div class="col-4">
      <%= label_tag :end_date, 'End Date', class: 'form-label' %>
      <%= datetime_field_tag :end_date, params[:end_date], class: 'form-control' %>
    </div>

    <div class="my-3">
      <%= submit_tag 'Search', class: 'btn btn-secondary'%>
    </div>
  </div>
<% end %>

<table class="table">
  <thead>
  <tr>
    <th>Serial Number</th>
    <th>User Email</th>
    <th>State</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <% @winners.each do |winner| %>
    <tr>
      <td><%= winner.bet.serial_number %></td>
      <td><%= winner.user.email %></td>
      <td><%= winner.state %></td>
      <td>
        <%= button_to 'Submit', submit_admin_winner_path(id:winner), data: { turbo: false }, method: :put if winner.may_submit? %>
        <%= button_to 'Pay', pay_admin_winner_path(winner), data: { turbo: false }, method: :put if winner.may_pay? %>
        <%= button_to 'Ship', ship_admin_winner_path(winner), data: { turbo: false }, method: :put if winner.may_ship? %>
        <%= button_to 'Deliver', deliver_admin_winner_path(winner), data: { turbo: false }, method: :put if winner.may_deliver? %>
        <%= button_to 'Publish', publish_admin_winner_path(winner), data: { turbo: false }, method: :put if winner.may_publish? %>
        <%= button_to 'Remove Publish', remove_publish_admin_winner_path(winner), data: { turbo: false }, method: :put if winner.may_remove_publish? %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>