config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: {
      registrations: 'client/registrations',
      sessions: 'client/sessions'
    }
    scope module: :client do

      root 'home#index', as: :client_root
      resource :profiles, only: [:edit, :update, :show] do
        put :cancel
      end
      resources :addresses, except: :show
      resource :invite, only: :show
      resources :lottery, only: [:show, :index, :create]
      resources :shop
      resources :shares, only: [:show, :index]
      resources :prize, only: [:show, :update] do
        resource :feedback, only: [:show, :update]
      end
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace 'admin', path: '' do
      devise_for :users, controllers: {
        sessions: 'admin/sessions'
      }, as: :admin
      root 'home#index'
      resources :users, only: :index
      resources :items, except: :show do
        member do
          put :start
          put :pause
          put :end
          put :cancel
        end
      end
      resources :categories, except: :show
      resources :winners, only: :index do
        member do
          put :submit
          put :pay
          put :ship
          put :deliver
          put :publish
          put :remove_publish
        end
      end
      resources :orders, only: :index do
        member do
          put :pay
          put :cancel
        end
      end
      resources :offers, except: :show
      resources :bets, only: :index do
        put :cancel
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :regions, only: %i[index show], defaults: { format: :json } do
        resources :provinces, only: :index, defaults: { format: :json }
      end
      resources :provinces, only: %i[index show], defaults: { format: :json } do
        resources :cities, only: :index, defaults: { format: :json }
      end

      resources :cities, only: %i[index show], defaults: { format: :json } do
        resources :barangays, only: :index, defaults: { format: :json }
      end

      resources :barangays, only: %i[index show], defaults: { format: :json }
    end
  end
end

app/models/address/barangay.rb
class Address::Barangay < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :city
end

app/models/address/city.rb
class Address::City < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :province
  has_many :barangays
end

app/models/address/province.rb
class Address::Province < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :region
  has_many :cities
end

app/controllers/client/addresses_controller.rb
class Client::AddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_address, only: [:edit, :update, :destroy]

  def index
    @addresses = current_user.addresses
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.user = current_user
    if @address.save
      flash[:notice] = 'Address created successfully'
      redirect_to addresses_path
    else
      flash.now[:alert] = 'Address create failed'
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @address.update(address_params)
      flash[:notice] = 'Address updated successfully'
      redirect_to addresses_path
    else
      flash.now[:alert] = 'Address update failed'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @address.destroy
    flash[:notice] = 'Address destroyed successfully'
    redirect_to addresses_path
  end

  private

  def set_address
    @address = current_user.addresses.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:address_region_id, :address_province_id,
                                    :address_city_id, :address_barangay_id, :genre, :name,
                                    :street_address, :phone_number, :remark, :is_default)
  end
end

app/controllers/client/feedbacks_controller.rb
class Client::FeedbacksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_winner

  def show; end

  def update
    if @winner.may_share? && @winner.update(winner_params)
      @winner.share!
      flash[:notice] = "Successfully updated"
      redirect_to profiles_path(category: 'winning')
    else
      render :show
    end
  end

  private

  def set_winner
    @winner = current_user.winners.delivered.find(params[:prize_id])
  end

  def winner_params
    params.require(:winner).permit(:comment, :picture)
  end

end

app/controllers/client/home_controller.rb
class Client::HomeController < ApplicationController
  def index; end
end

app/controllers/client/invites_controller.rb
class Client::InvitesController < ApplicationController
  before_action :authenticate_user!

  def show
    @promote_url = "#{request.host_with_port}#{new_user_registration_path}?promoter=#{current_user.email}"
    qrcode = RQRCode::QRCode.new(@promote_url)

    @svg = qrcode.as_svg(offset: 0, color: "000", shape_rendering: 'crispEdges',
                         module_size: 6, standalone: true)
  end
end

app/controllers/client/lottery_controller.rb
class Client::LotteryController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @items = Item.active.starting.where("offline_at >= (?) AND online_at <= (?)", Date.current, Date.current)
    @items = @items.includes(:categories).where(categories: { id: params[:category] }) if params[:category].present?
  end

  def show
    @item = Item.active.starting.where("offline_at >= (?) AND online_at <= (?)", Date.current, Date.current).find(params[:id])
    @bet = Bet.new
    @bets = current_user.bets.where(item: @item, batch_count: @item.batch_count)
    @progress = (Bet.where(item: @item, batch_count: @item.batch_count).count/@item.minimum_bets.to_f) * 100
  end

  def create
    bet_counts = params[:bet][:bet_count]
    bet_counts.to_i.times do |bet_count|
      bet = Bet.create(batch_count: params[:item_batch_count],
                     user_id: current_user.id, item_id: params[:item_id])
      if bet.errors.any?
        flash[:notice] = "#{bet.errors.full_messages}, #{bet_count} bets created"
        break
      elsif bet_count == bet_counts.to_i
        flash[:notice] = 'Successfully created'
      end
    end
    redirect_to lottery_path(id: params[:item_id])
  end

end

app/controllers/client/prize_controller.rb
class Client::PrizeController < ApplicationController
  def show
    @winner = Winner.find(params[:id])
  end

  def update
    @winner = Winner.won.find(params[:id])
    if @winner.update(address_id: params[:winner][:address_id])
      @winner.claim!
      flash[:notice] = "Successfully updated"
      redirect_to profiles_path(category: 'winning')
    else
      flash[:alert] = "Fail to update"
      render :show
    end
  end

end

app/controllers/client/profiles_controller.rb
class Client::ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @orders = current_user.orders if params[:category] == 'orders'
    @bets = current_user.bets if params[:category] == 'lottery'
    @members = current_user.children if params[:category] == 'invites'
    @winnings = current_user.winners if params[:category] == 'winning'
  end

  def edit
    @client = current_user
  end

  def update
    @client = current_user

    if @client.update(update_without_password_params)
      redirect_to profiles_path, notice: "Successfully Updated"
    else
      @client.update(update_with_password_params)
      redirect_to profiles_path, notice: "Successfully Updated"
    end
  end

  def cancel
    @order = Order.find(params[:id])
    if @order.cancel!
      flash[:notice] = 'Cancelled Successfully'
    else
      flash[:alert] = @order.errors.full_messages.join(', ')
    end
    redirect_to profiles_path(category: 'orders')
  end

  private

  def client_params
  end

  def update_without_password_params
    params.require(:user).permit(:phone_number, :username, :image)
  end

  def update_with_password_params
    params.require(:user).permit(:username, :email, :phone_number, :image, :password)
  end
end

app/controllers/client/registrations_controller.rb
# frozen_string_literal: true

class Client::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    cookies[:promoter] ||= params[:promoter]
    super
  end

  # POST /resource
  def create
    super
    parent = User.find_by(email: cookies[:promoter])
    self.resource.update(parent: parent)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/client/sessions_controller.rb
# frozen_string_literal: true

class Client::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end
  def create
    user = User.find_by(email: params[:user][:email])
    if user&.client?
      super
    else
      flash[:alert] = "Wrong email or password"
      redirect_to new_user_session_path
    end
  end
  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/client/shares_controller.rb
class Client::SharesController < ApplicationController
  before_action :set_winner, only: :show

  def show; end

  def index
    @winners = Winner.published
  end

  private

  def set_winner
    @winner = Winner.includes(:user).find(params[:id])
  end
end

app/controllers/client/shop_controller.rb
class Client::ShopController < ApplicationController
  before_action :authenticate_user!, only: :create
  before_action :set_offer, except: [:index, :create]

  def index
    @offers = Offer.active
  end

  def show
    @offer = Offer.find(params[:id])
    @order = Order.new
  end

  def create
    @offer = Offer.find_by(id: params[:order][:offer_id])
    @order = Order.new(offer_id: @offer.id)
    @order.amount = @offer.amount
    @order.coin = @offer.coins
    @order.user = current_user
    @order.genre = :deposit
    @order.offer = @offer
    if @order.save
      @order.submit!
      flash[:notice] = "Your purchase is complete"
    else
      flash[:alert] = @order.errors.full_messages.join(', ')
    end
    redirect_to shop_index_path
  end

  private

  def set_offer
    @offer = Offer.active.find(params[:id])
  end

end

app/helpers/client/home_helper.rb
module Client::HomeHelper
end

app/views/client/addresses/_form.html.erb
<div class="align-middle my-5">
  <div class="container d-block justify-content-center w-50">
    <%= form_with model: address, data: { controller: :location } do |form| %>
      <% if address.errors.any? %>
        <ul>
          <% address.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      <% end %>

      <div class="mb-3">
        <%= form.label :name, class: 'form-label' %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :street_address, class: 'form-label' %>
        <%= form.text_field :street_address, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :is_default %>
        <%= form.check_box :is_default %>
      </div>

      <div class="mb-3">
        <%= form.label :remark, class: 'form-label' %>
        <%= form.text_area :remark, class: 'form-control' %>
      </div>

      <div class="form-check form-check-inline">
        <%= form.collection_radio_buttons :genre, Address.genres, :first, :first, class: 'form-check-label'  %>
      </div><br>

      <div class="mb-3">
        <%= form.label :address_region_id, class: 'form-label' %>
        <%= form.collection_select :address_region_id,
                                   Location::Region.all, :id, :name,
                                   { prompt: 'Please select region' },
                                   data: { location_target: 'selectedRegionId', action: 'change->location#fetchProvinces' }, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :address_province_id, class: 'form-label' %>
        <%= form.collection_select :address_province_id,
                                   [], nil, nil,
                                   { prompt: 'Please select province' },
                                   data: { location_target: 'selectProvinceId', action: 'change->location#fetchCities' }, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :address_city_id, class: 'form-label' %>
        <%= form.collection_select :address_city_id,
                                   [], nil, nil,
                                   { prompt: 'Please select city' },
                                   data: { location_target: 'selectCityId', action: 'change->location#fetchBarangays' }, class: 'form-control' %>

      </div>

      <div class="mb-3">
        <%= form.label :address_barangay_id, class: 'form-label' %>
        <%= form.collection_select :address_barangay_id,
                                   [], nil, nil,
                                   { prompt: 'Please select barangay' },
                                   data: { location_target: 'selectBarangayId' }, class: 'form-control' %>
      </div>

      <div class="actions"><br>
        <%= form.submit class: 'btn btn-secondary w-100' %>
      </div>
    <% end %>

  </div>
</div>

app/views/client/addresses/edit.html.erb
<%= render partial: 'form', locals: {address: @address } %>

app/views/client/addresses/index.html.erb
<h1>Address</h1>
<%= link_to 'New', new_address_path, class: 'btn btn-secondary btn-sm' %>
<table class="table">
  <thead>
  <td>Name</td>
  <td>Street Address</td>
  <td>Default</td>
  <td>Remark</td>
  <td>Genre</td>
  <td>Address</td>
  </thead>
  <% @addresses.each do |address| %>
    <tr>
      <td><%= address.name %></td>
      <td><%= address.street_address %></td>
      <td><%= address.is_default %></td>
      <td><%= address.remark %></td>
      <td><%= address.genre %></td>
      <td><%= "#{address.street_address}, #{address.barangay&.name}, #{address.city&.name}, #{address.province&.name}, #{address.region&.name}" %></td>
      <td>
        <%= link_to 'Edit', edit_address_path(address) %>
        <%= button_to 'Delete', address_path(address), method: :delete %>
      </td>
    </tr>


<% end %>
</table>

app/views/client/addresses/new.html.erb
<%= render partial: 'form', locals: { address: @address } %>